### ISSUE TITLE
Design Web GUI

### ISSUE THREAD

**Issue by roudra-das** [barry802/FD-APAC-AI-Project#5]
Can build a static page with Github.
Looking into use of django to build functional web interface.
Should be able to deploy on Heroku for free?
Do we need a domain?

Superuser: admin
Pass: FDSydney1234

**Comment by roudra-das** [comment]
Created basic landing page with django
![Screenshot_20240607_144546](https://github.com/barry802/FD-APAC-AI-Project/assets/50075143/63535822-23d0-45a2-b5da-0884ddbe01af)

**Comment by barry802** [comment]
Nice!

**Comment by barry802** [comment]
Whats the IP?

**Comment by roudra-das** [comment]
I havent deployed it yet
its running off the codespace atm
https://studious-spoon-9jg59jvpxvg297x4-8000.app.github.dev/

**Comment by roudra-das** [comment]
## TO-DO:

- [ ] Initialize django project
- [ ] Complete login interface
- [ ] Deploy to a vps like Heroku

**Comment by roudra-das** [comment]
@kelvouttt I was able to fix the API calls using the python-decouple library
However, when push to the branch, it flagged that an API key may be hard coded.
Can you please check if there are any vulnerabilities?
